appearance:
  default: system
  switcher: true

theme:
  colors:
    primary:
      light: "#2563eb"
      dark: "#3b82f6"
    accent:
      light: "#c2410c"
      dark: "#fdba74"

plugins:
  components:
    "@evidence-dev/core-components": {}
  datasources:
    "@evidence-dev/snowflake": {}
